src/main/java/org/jboss/pnc/bacon/cli/Pnc.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/BrewPush.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Build.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/BuildConfiguration.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Environment.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GenerateTools.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GroupBuild.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GroupBuildConfiguration.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Product.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductMilestone.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductRelease.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductVersion.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Project.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Repository.java
This commit implements the suggestion for PNC sub-commands as specified
in NCL-3608
There are no real logic implemented yet. This will be added in
subsequent commits
=> [NCL-3608] Initial skeleton for PNC sub-commands

auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java
Thanks for the suggestion @michalszynkiewicz !
=> [NCL-4338] call setupUnirest in a static block

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
Connected with: https://github.com/project-ncl/pnc/pull/2426
=> [NCL-3768] Add cli option to download sources of build

cli/pom.xml, common/pom.xml, config.yaml, pig/pom.xml, pnc/pom.xml, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pom.xml
=> [NCL-4762] Use new PNC client jar

pom.xml
Thanks to @dwalluck for the suggestion!
=> Enforce ban duplicate deps

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java
=> Show nicer error when missing required argument/option

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
=> [NCL-4287] Add example section if user overrides exampleText method

auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java
Commit changes saved-used.json cache file permissions to "-rw-------"
=> [NCL-5444] CLI cache file for token should have permission 600

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
This occurs for:
```
<jar> pnc build start -h
```
=> [NCL-5522] Fix NPE when printing help option

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java
Predisposition: https://github.com/project-ncl/pnc/pull/2895
=> [NCL-5406] add websocket support to CLI

config/src/main/java/org/jboss/pnc/bacon/config/Config.java
=> [NCL-5594] Provide user with example config.yaml

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/ByExtensionCollectingVisitor.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusExtension.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusExtensions.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/runtime/CommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/da/CommunityDependency.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/MavenRepositoryUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/ResourceUtils.java
=> [WIP] Add Quarkus AddOn

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncConfigurator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/PncClientUtils.java
Test yaml used:
```yaml
product:
name: ProductB # full product name
abbreviation: testb # official product name abbreviation - used to create the brew/koji tag name
stage: Alpha1 # product phase, if we're targetting GA, should be GA, etc
issueTrackerUrl: http://issues.jboss.org/browse/TEST
version: 1.2.0
milestone: ER1
group: ProductA 1.2 all # name of the PNC build group
```
=> Fix pig errors

pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
This follows the rename on the orch side
=> Rename Banner import

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/XmlUtils.java
Adding code to check for invalid licenses in the license XML file. Also added description of the invalid licenses along with groupid and artifactid
=>  Adding code to check for invalid licenses in license xml file

common/src/main/java/org/jboss/pnc/bacon/common/futures/FutureUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
That'll fail until https://github.com/project-ncl/pnc/pull/3093 is merged.
=> Add websocket support for scm repository

bacon_install.py
Thanks to @janinko for reporting this issue! <3
=> Don't add newline at the beginning of bash shebang

.gitignore, common/src/main/java/org/jboss/pnc/bacon/common/Utils.java, pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/da/DADao.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/ArtifactWrapper.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/common/ParameterChecker.java, pom.xml
There are still some other bugs to be fixed, but commiting this for now.
=> Pig bug fixes

cli/pom.xml
=> Remove plexus plugin

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/test/java/org/jboss/pnc/bacon/config/ConfigReaderTest.java, pig/src/test/resources/build-config-UnknownVar.yaml, pig/src/test/resources/build-config-VarUsage.yaml
=> Issue #247 : Allow whitespace in variable names

config/src/main/java/org/jboss/pnc/bacon/config/DaConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/IndyConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/KeycloakConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/PigConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/PncConfig.java, integration-tests/src/test/resources/config/config.yaml, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> Add validation to pig config, and fix compilation error

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java
And also provide a flag to build with no build dependencies
(--no-build-dependencies)
=> [NCL-5895] Build the dependencies by default

common/src/main/java/org/jboss/pnc/bacon/common/Constant.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/ExtraDeliverableDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/DocumentGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/da/DADao.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/nvr/NvrListGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/script/ScriptGenerator.java, pig/src/test/resources/empty/build-config.yaml
=> Release storage url as param

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java
From @michalszynkiewicz:
For a successful build, it makes no sense to download the build log,
this thing can be huge.  We should not download the log and print it
to the console
This commit only downloads and prints the build logs if an error happens.
Fixes #274
=> [#274] Don't download and print build logs if successful

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductReleaseCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
Thanks @rnc for pointing out the bad wording!
=> [#295] Better word 'get' command descriptions

common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java, common/src/test/java/org/jboss/pnc/bacon/common/ObjectHelperTest.java
Fix mix of charsets UTF-8 and default in ObjectHelperTest
=> Fix swapped argument order in assert statements in ObjectHelperTest

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
=> add a add-dependency command to bacon

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
There are still many places in the code where clients still aren't being closed. One place where it's difficult to close them is when they are initialized in the constructor of a class.
=> Close PNC clients in PigFacade

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java
It is done by filtering by start time rather than submit time.
Thanks @djcoleman for finding this bug!
=> [NCL-5987] Properly grab the latest group build

bacon_install.py
This makes it possible to specify the version to install as the
parameter. If a version if specified, script tries to install it.
If the version is specified as "snapshot", it tries to
install latest snapshot release.
If no version is specified, latest released version is installed.
=> Allow to install specific version of Bacon

pig/src/main/resources/README.ftl
Special thanks to @goldmann for reporting and @michalszynkiewicz for
providing the fix :)
=> [NCL-6001] Adjust the build url in README.md

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ParentPomDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/script/ScriptGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/CSVUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/HashUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/MavenRepositoryUtils.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/BifrostClient.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
=> Close streams for Files.walk/list, GenericSettingClient, and CSV

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java
=> Use entrySet rather than get when walking through map

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/nvr/NvrListGenerator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/nvr/NvrListGeneratorTest.java, pom.xml
* [hell no!] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
* [nope] Have you added unit tests for your change?
=> change nvr list generator to use paths

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/javadoc/JavadocManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java
=> Fix Logger and String.format statements

pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java
=> [NCL-5991] Add pnc group-config show-latest-build command

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
This will allow the user to say we don't want an external-scm for that
scm repository.
If both the '--no-external-scm' and '--external-scm <value>' are
specified, then a validation fails and prevents the user to proceed.
The '--no-external-scm' automatically sets the preBuild to false.
=> [NCL-5927] Add --no-external-scm flag for scm-repository update

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/NotYetAlignedFromDependencyTree.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/javadoc/JavadocManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
=> Close resources

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductReleaseCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/WhoAmICli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/AnnouncementBannerCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/MaintenanceModeCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/common/ClientCreator.java
=> Close PNC clients

auth/pom.xml, cli/pom.xml, common/pom.xml, config/pom.xml, da/pom.xml, integration-tests/pom.xml, pig/pom.xml, pnc/pom.xml, pom.xml, test-common/pom.xml
=> Apply sortpom-maven-plugin

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> no NPE on repo generation: IGNORE

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java
While checking for the ref of a tag, we forgot to specify the tag
relative to the remote name. This commit fixes this issue.
Special thanks to @AntStephenson for reporting the issue and providing
the debugging logs to help find the bug easily!
=> Fix logic on how to find refs

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
=> pig: remove config from build group if no longer defined

auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java
When we refresh an access token, we usually also get a new refresh
token. However the lifetime of the new refresh token has the same expiry
date as the original refresh token.
Even when we get a new access token with a refresh token, if the
particular refresh token lifetime is less than the normal lifetime of an
access token, the new access token will get the lifetime of the refresh
token.
Those 2 combinations mean that the access token lifetime, even after
refreshing it to get new ones, is the lifetime of a refresh token.
If the refreshed access token expires in fewer hours than we'd like, we
should instead get a new set of access / refresh token by asking her
password again
=> [NCLSUP-115] Improve logic on when refresh token is ok

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileUtils.java, pig/src/main/resources/rh-license-names.json, static-resources/CC0-1.0.txt, static-resources/CDDL+GPL-1.1, static-resources/CDDL-1.1.txt, static-resources/EPL-1.0.txt, static-resources/EPL-2.0.txt, static-resources/UPL-1.0.txt, static-resources/deprecated_LGPL-2.1+.txt, static-resources/mysql-license.txt
=> Fix repo gen add license overrides

pig/src/main/resources/rh-license-names.json
=> fix license text urls

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java
=> [NCL-6022] Fix bug where executionRoot should be brewBuildName

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOn.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/ExtraDeliverableDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/runtime/CommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/runtime/RuntimeDependenciesAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/spring/BomVerifierAddon.java
=> maven repo generation fixed, quarkus community dep analyzer fixed

bacon_install.py
e.g:
```
Something wrong happened while downloading the link: https://repository.jboss.org/nexus/content/repositories/snapshots/org/jboss/pnc/bacon/cli/2.0.3-SNAPSHOT/cli-2.0.3-20200909.154302-4-shaded.jar :: HTTP Error 404: Not Found
```
=> Print reason why script failed

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/BrewSearcher.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/SharedContentReportGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/SharedContentReportRow.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/BuildFinderUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java
=> [NCL-6028] properly parallelize KBF search for brew info in shared content building

pig/src/main/resources/rh-license-exceptions.json
=> Add agroal 1.8 license

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
=> retry downloads

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
=> Fix typo in command definition

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
=> download retry fixes

integration-tests/pom.xml, integration-tests/src/test/java/org/jboss/pnc/bacon/test/TestType.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/EmptyProjectBuildTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigFunctionalTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pnc/ProductTest.java, integration-tests/src/test/resources/config/config.yaml, integration-tests/src/test/resources/empty/build-config.yaml, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java
=> pig test against real PNC

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
=> pig: move up setting temp build

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java
=> use latest successful build if `skipBuilds` is used

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractGetSpecificCommand.java
=> Improve handling of exceptions. Improve tests

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractBuildListCommand.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractListCommand.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
=> NCL-6033: List operations on bacon are broken

bacon_install.py
Thanks to @dwalluck for the idea!
=> [Install script] Exponential backoff during retries

cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java
Close terminal in App in order to restore the original state.
Fix failures in testHelp() and testProfile() due to ANSI codes in output.
Fix failure in testConfigPath() due to file separators.
Fix failure in testProfile() due to line separators.
Fix failure in testPigTempBuild() due to no exception thrown by tapSystemErr().
Use AssertJ to get meaningful assertion failure messages.
=> Close terminal in App and fix test failures in AppTest

README.md
=> Link to the existing documentation guides

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
=> [NCL-6048] Remove --skipRepo from bacon pig

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoDescriptor.java
=> make -r work, change devtoolsJarName for Quarkus addon

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, common/src/main/java/org/jboss/pnc/bacon/common/Constant.java
=> Enable history in bacon shell

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/EmptyProjectBuildTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/out/PigBuildOutput.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java
=> [NCL-6043] noWait support for bacon pig build

pig/src/main/resources/rh-license-exceptions.json
=> Added license exceptions for Fuse.

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Quarkus add on: add classifier support to non-existent deps report

pig/src/main/resources/rh-license-exceptions.json, pig/src/main/resources/rh-license-names.json
=> Adding license exceptions and adding a URL alias to GNU GPL 2.0

auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java
=> Improve log messages in CacheFile and log exceptions on error

auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java
=> Check for posix support before trying to set posix file permissions

auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java
=> Use singleton map instead of hashmap for storing single entry

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> [NCL-6097] bacon is missing possibility to set a milestone as current

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> Fix newlines in picocli output

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncConfigurator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilderTest.java
=> NCL-6054: Close PNC clients used by PiG

auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java
=> Throw exception instead of returning null in refreshToken()

common/src/main/java/org/jboss/pnc/bacon/common/cli/JSONCommandHandler.java
=> Fix string concatenation in log statement in JSONCommandHandler

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> Fixed the invocation of the PrintWriter constructor

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
=> [NCLSUP-161] Set default attempts to 5

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
Thanks @AntStephenson for the feedback!
=> [NCLSUP-161] Change max backoff time to 30 seconds

cli/pom.xml, pom.xml
=> NCL5978 Revert changes for new PME release

bacon_install.py
=> CPAAS-976 Allow specifying help/target location

bacon_install.py
=> CPAAS-976 Ignore version tag if its latest

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/VersionProvider.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/AbstractTest.java
=> CPAAS976 Always print version

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
=> [NCL-6170] Bacon build list command is ignoring some arguments

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java
=> [NCL-6110] Print status of brew push on stdout

pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzer.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzerTest.java, pig/src/test/resources/__files/build-stub.html, pig/src/test/resources/__files/community-deps1.csv, pig/src/test/resources/__files/community-deps2.csv, pig/src/test/resources/__files/expectedPostBuildInfo.txt, pig/src/test/resources/__files/repository-artifact-list1.txt, pig/src/test/resources/__files/repository-artifact-list2.txt
=> Adding post build analysis for artifacts

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/RepoGenerationData.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/ArtifactWrapper.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGeneratorTest.java
=> Bxmsprod 1026

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGenerator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGeneratorTest.java
=> Fix formatting of codebase

auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java
The original version called `new File(configFolder).mkdirs()` without checking for failure. Then it could fail unexpectedly later. I replaced with `Files.createDirectories(path)` which throws an `IOException`. I also removed `fileExists()` and replaced with separate calls to `Files.isRegularFile()` and `Files.isDirectory()` so that we check the actual type as opposed to just the existence.
=> Handle failure to create cache file directories by throwing exception

_includes/header.html
=> Fix stylesheet reference

_config.yml, _includes/header.html
=> Attempt to fix stylesheets

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Fix devtoolsJarName for quarkus-bom and quarkus-product-bom

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigValidator.java
=> [NCL-6182] add a environmentName parameter to build-config.yaml

guide/build-config.md
=> [NCLSUP-171] Document vars in yaml + define vars in cli

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java
=> [NCL-6200] Print pre-processed build-config.yaml

guide/build-config.md
To be merged after #549  and #537
=> [NCL-6200] Document pig pre-process-yaml

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileUtils.java
=> [NCLSUP-178] Bacon pig source fails with NoSuchFileEx

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Add coreOnly config

guide/build-config.md
Should be merged after https://github.com/project-ncl/bacon/pull/552
=> [NCL-6182] update gh-pages documentation to include environmentName

pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/HashUtilsTest.java
Thanks to @michalszynkiewicz for pointing this out!
=> [NCLSUP-174] Add missing assert for test

integration-tests/src/test/java/org/jboss/pnc/bacon/test/Endpoints.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
=> [NCL-6235] enable systemImageId property to fetch deprecated environment and add a warning

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
=> [NCLSUP-198] IGNORE strategy is not used when running 'pig run'

guide/build-config.md
=> [NCL-6235] update documentation to reflect recent changes to environment handling

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzer.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzerTest.java, pig/src/test/resources/__files/expectedPostBuildInfo.txt, pig/src/test/resources/__files/nonexistent-redhat-deps1.txt, pig/src/test/resources/__files/nonexistent-redhat-deps2.txt
* [] Have you added a note in the [CHANGELOG wiki](https://github.com/project-ncl/bacon/wiki/Changelog) for your change if user-facing?
=> Adding post build analysis for nonredhat dependencies

DEVELOPING.md
=> Update developer's guide with contribution requirements

pom.xml
=> Reverting jaxb version to 2.2.11 due to failures while running QuarkusCommunityDepAnalyzer add-on

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoBuilder.java
=> Repository generation - add additionalRepo only if it is defined

pig/src/main/resources/rh-license-exceptions.json
=> Adding a version pattern instead of hard-coded versions

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/BuildConfigTest.java
=> [NCLSUP-229] Add validation for build config name

guide/pig.md
=> [NCLSUP-222] Add comment on how to override env var

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Revert "Change devtoolsJarName in QuarkusCommunityDepAnalyser"

guide/build-config.md
=> [NCLSUP-210] Expand Maven Repository generation Documentation for Bacon

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
=> [NCLSUP-244] release: only generate script+nvr list if data present

guide/pig.md
Added some docs about generating a manifest for the offliner tool & docs for including or excluding artifacts from the repository generation phase. I see there are a bunch of different strategies in PiG that I don't use so I've just added a foundation for them to be explained by someone else.
=> Update docs with some repo generation bits & offliner manifest generation

pig/pom.xml, pig/src/main/resources/rh-license-exceptions.json, pig/src/test/java/org/jboss/pnc/bacon/resources/ResourcesValidationTest.java, pom.xml
=> [NCL-6328] Review regexps in rh-license-exceptions.json

guide/build-config.md, guide/pig.md
=>  Move the detailed maven strategy to build-config.md

guide/build-config.md
Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>
=> Document excludeSourceBuilds field in GH Pages

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Skipping tests while building temporary project

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
cc @michalszynkiewicz  @harshmadhani 
could you see review this?
=> Update devtoolsJarName for product-bom

pig/src/main/resources/rh-license-exceptions.json
=> Adding json-patch and jackson-coreutils to exceptions list

pig/src/main/resources/rh-license-exceptions.json
=> Adding licenses for "com.github.java-json-tools jackson-coreutils" and "com.github.java-json-tools json-patch"

guide/build-config.md
=> Provide additional product documentation and point to example file

cli/src/main/resources/logback-test.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ExternalArtifactDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
=> [NCLSUP-264] Reduce bacon logging

pig/src/main/resources/rh-license-exceptions.json
=> Adding exceptions for btf and msg-simple

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java
=> Provide user with more error info if running without verbose flag

guide/build-config.md
=> [NCLSUP-305] Document releaseStorageUrl usage in bacon/pig documentation

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/common/DeliverableManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/da/DADao.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
=> Logging improvements

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java
=> [NCL-6473] Bacon should improving reports for build groups

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java
=> [NCL-6464] add warning when running not supported temp build

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/VertxArtifactFinder.java
CC @RotBolt @harshmadhani 
This is a draft PR for "Automate the creation of vertx artifacts list which are used in quarkus".
=> Automate creation of vertx artifacts list which are used in quarkus

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pom.xml
=> Bump formatter-maven-plugin from 2.14.0 to 2.15.0

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/resources/README.ftl
=> [NCLSUP-266] Dont display ignored parts of generated html readme

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java
=> [NCLSUP-344] Properly escape repositories for extra repositories

guide/hints.md
=> [NCLSUP-306] Document disabling color output

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pom.xml
=> [NCL-6505] Add ability to specify brewPullActive in Bacon

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
=> Fix brew pull flag formatting

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/main/resources/logback.xml, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java
@thescouser89 No tests yet but I think this solves the highlighting issue...
=> Correct highlighting when colour is enabled. Rename logback.xml

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pom.xml
=> Support for sbt build type

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
=> Remove temporary build text on warning

guide/build-config.md
=> [NCL-6676] Document buildCategory parameter in pig configuration

example-pig-config.yaml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java
=> [NCL-6676] Add BUILD_CATEGORY to bacon

guide/build-config.md
=> Add documentaion for RESOLVE_ONLY strategy

.gitignore, guide/pig.md
@jomrazek @rnc 
Mentioning @michalszynkiewicz too because he is the author of the addon
=> Add documentation for extraDeliverablesDownloader addon

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java
=> [NCLSUP-416] Add cancel option to bacon pig CLI

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
=> Add `pnc builg get-align-logs` command

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Check if the JSON file path is correct

example-pig-config.yaml, integration-tests/src/test/resources/empty/build-config.yaml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigValidator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/BuildConfigTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigCheckTest.java, pig/src/test/resources/build-config-UnknownVar.yaml, pig/src/test/resources/build-config-VarUsage.yaml, pig/src/test/resources/build-config-environment-override.yaml
=> [NCL-5983] Deprecate external scm url

guide/build-config.md
=> [NCL-5983] Document - deprecate external scm url

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> [NCL-6719] Created command to submit Deliverable analysis

pig/src/main/resources/rh-license-exceptions.json
cc @SaumyaSingh1 @paulgallagher75
=> Adding connect-file and connect-transforms to license exception list

bacon_install.py
Remove this commit once outage is over
=> Use alternative url to download bacon snapshot

bacon_install.py
This reverts commit c43cd57c089ee803c5243c3d11060ce94b5f2ad2.
=> Revert "Use alternative url to download bacon snapshot"

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java
=> NCL-6735 Handle external and internal SCM

guide/pig.md
=> [NCL-6714] Document pig export build-config feature

pig/src/test/resources/resolve-and-repackage-repo-artifact-list.txt, pom.xml
=> [NCL-6786] Migrate to java 11

index.md
The Mac section is contributed by @alexcreasy
=> [NCLSUP-245] Add Mac section for installation

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/documents/Template.java, pig/src/main/resources/BUILD_LIST.ftl
> Added: Add build list to extras
> No, should I add a unit test for this improvement?
=> Add build list to extras

guide/build-config.md, guide/configuration.md, guide/pig.md, index.md
=> Rename master to main - DOC

bacon_install.py
This commit also makes use of the checksum to check if we already have
the latest bacon.jar installed before attempting to download the latest
one.
=> [NCLSUP-469] Add checksum check for downloaded bacon jar

bacon_install.py
This applies for the bacon_install.py
=> Print the correct installed version if custom version specified

pom.xml
Reverts project-ncl/bacon#854
2.2.0 has not been deployed yet
=> Revert "Bump pnc.version from 2.2.0-SNAPSHOT to 2.2.0"

pig/src/main/resources/rh-license-exceptions.json
=> added license details for com.thoughtworks.xstream

pig/src/main/resources/rh-license-exceptions.json
=> added the correct license link for 5 artifacts

.github/dependabot.yml
This reverts commit a4b846d0b4c123af904be8be2876a28d9aa57ad0.
=> Revert "Remove dependabot.yaml"

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
=> Better error message in QuarkusCommunityDepAnalyzer

guide/build-config.md
=> [NCL-5981] Document use of `outputSuffix`

index.md
=> [NCLSUP-476] Add info on JDK and TLS cert

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/EmptyProjectBuildTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pom.xml
=> [NCL-6917] add dry-run option

da/src/main/java/org/jboss/bacon/da/DABlockListCli.java, da/src/main/java/org/jboss/bacon/da/Da.java, da/src/main/java/org/jboss/bacon/da/DaHelper.java
=> Add blocklist support for DA

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/camel/RuntimeDependenciesToAlignTree.java
Add camel addon for build-from-source statistics and info
=> Add camel addon for build-from-source statistics and info

guide/pig.md
Added doc for runtimeDependenciesToAlignTree addOn.
=> Add documentation on runtimeDependenciesToAlignTree addOn

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java
=> CPAAS-1521 Ensure empty releaseStorageUrl parameter is detected

da/src/main/java/org/jboss/bacon/da/DAReportsCli.java, da/src/main/java/org/jboss/bacon/da/Da.java, da/src/main/java/org/jboss/bacon/da/rest/endpoint/ReportsApi.java, pom.xml
=> Add DA report commands

pom.xml
=> Update DA and PNC to released versions

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> Hide deliverable analysis commands

guide/build-config.md
parameters.resolveExcludes of RESOLVE_ONLY zip repo generation strategy
depends on https://github.com/project-ncl/bacon/pull/919
=> Document the new options parameters.resolveIncludes and

stylesheets/stylesheet.css
=> Change style .inner max-width from absolute 640px to relative 75%

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
=> Improve description and explain what dry-run means

cli/pom.xml
=> Skip python test when skipTests is on

pig/src/main/resources/rh-license-exceptions.json
=> scala-logging_2.12 license added

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/EmptyProjectBuildTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigFunctionalTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/PigContextTest.java
=> [NCLSUP-624] make releaseStorage optional when unnecessary

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java
=> Give user information with what status build failed

pig/src/main/resources/rh-license-exceptions.json
=> Add hapi-base to rh-license-exceptions list to fix the license issue.

guide/pig.md
Corresponding documentation change for the change in https://github.com/project-ncl/bacon/pull/940
=> Documentation changes for printProjectLogs

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/EmptyProjectBuildTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/AlignmentType.java
=> [NCL-7040] Add option to set dry-run build option from build-config.yaml

guide/build-config.md
=> Add documentation for dry-run setup from build-config.yaml

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GavSet.java
Could please somebody review? 
Here are the docs changes: https://github.com/project-ncl/bacon/pull/945
=> Allow RESOLVE_ONLY repo generation against multiple BOMs

.gitignore, guide/build-config.md
related to https://github.com/project-ncl/bacon/pull/942
=> Document RESOLVE_ONLY repo generation against multiple BOMs

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> [NCLSUP-671] Only add Maven dependencies that have redhat in the version

pig/src/main/resources/rh-license-exceptions.json
=> Adding licenses

guide/build-config.md, guide/pig.md
=> PiG addon for using CPaaS Product Security Scan as a Service documentation

da/src/main/java/org/jboss/bacon/da/DABlockListCli.java, da/src/main/java/org/jboss/bacon/da/DALookupCli.java, da/src/main/java/org/jboss/bacon/da/DAReportsCli.java
=> [NCL-7147] Honor the --jsonOutput flag for DA commands

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GavPattern.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/GavPatternTest.java
This adds resolveArtifacts parameter of RESOLVE_ONLY Maven repo generation strategy. The usage is explained in this docs PR: https://github.com/project-ncl/bacon/pull/950
=> Add resolveArtifacts parameter of RESOLVE_ONLY

da/src/main/java/org/jboss/bacon/da/DALookupCli.java, da/src/main/java/org/jboss/bacon/da/DaHelper.java
=> [NCL-7146] Order the DA lookup result based on input

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOn.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/ExtraDeliverableDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/camel/RuntimeDependenciesToAlignTree.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/microprofile/MicroProfileSmallRyeCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/VertxArtifactFinder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/runtime/RuntimeDependenciesAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/PostBuildScanService.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/spring/BomVerifierAddon.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/NotYetAlignedFromDependencyTree.java
=> [NCLSUP-690] Add option for --skipAddon for pig cli

guide/pig.md
=> [NCLSUP-690] Document the --skipAddon option for pig

da/src/main/java/org/jboss/bacon/da/DAReportsCli.java
=> Add new functionality to get versions by providing a GAV

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
=> [NCL-7274] Bacon getting build logs ends with premature end of chunk

pig/src/main/resources/rh-license-exceptions.json
=> Added extra license exceptions for jgit artifacts

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pom.xml
=> [NCL-7294] update for field name change in REST API

da/src/main/java/org/jboss/bacon/da/DAReportsCli.java
=> Adding functionality to filter available GAV with brew availability and artifact type

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
=> [NCL-7262] Add build configuration clone support

da/src/main/java/org/jboss/bacon/da/DALookupCli.java
=> Improve lookup command descriptions

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> [NCL-7323] Unhide delan commands and print output

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> Change deliverable analyzer URL parameter name

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> Add operation get-deliverables-analysis command

da/src/main/java/org/jboss/bacon/da/DALookupCli.java, da/src/main/java/org/jboss/bacon/da/DaHelper.java, da/src/test/java/org/jboss/bacon/da/DaHelperTest.java
Depracate --temporary and --managed-service parameters.
=> [NCL-7380] Introduce --lookup-mode parametr for DA lookup

guide/build-config.md
=> Add documentation for new sources strategies

auth/pom.xml, cli/pom.xml, common/pom.xml, config/pom.xml, da/pom.xml, integration-tests/pom.xml, pig/pom.xml, pnc/pom.xml, pom.xml, test-common/pom.xml
=> Update bacon + pnc version

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
=> Fix ConcurrentModificationException when generating extended sources

pig/src/main/resources/rh-license-exceptions.json
For #987  :)
cc @AntStephenson  @thescouser89
=> change keyword to version-regexp

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
=> [NCLSUP-795] Check if product version set in group config

guide/build-config.md
The functionality is implemented in https://github.com/project-ncl/bacon/pull/995
=> Paragraph about multi step Maven repo generation

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, common/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/OTELHelper.java, da/src/main/java/org/jboss/bacon/da/CustomRestHeaderFilter.java, da/src/main/java/org/jboss/bacon/da/DaHelper.java, pig/src/test/resources/resolve-and-repackage-repo-artifact-list.txt, pom.xml
=> NCL-7430 Add OpenTelemetry instrumentation

cli/pom.xml, pom.xml
=> Update to opentelemetry-ext-cli-java 1.2.0

da/src/main/java/org/jboss/bacon/da/CustomRestHeaderFilter.java
=> Add tracestate

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
=> [NCLSUP-796] Builds always return DR1 version

temp-name/src/main/java/org/jboss/bacon/tempname/impl/projectfinder/FoundProject.java, temp-name/src/main/java/org/jboss/bacon/tempname/impl/projectfinder/FoundProjects.java
=> Change type for buildConfig in FoundProject

pom.xml, temp-name/pom.xml, temp-name/src/main/java/org/jboss/bacon/tempname/impl/dependencies/DependencyResolver.java
=> Add first draft of DependencyResolver for Autobuilder

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/nvr/NvrListGenerator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/nvr/NvrListGeneratorTest.java
=> Set IncludeNotFound to false as not found artifacts are ignored anyway

temp-name/pom.xml, temp-name/src/main/java/org/jboss/bacon/tempname/impl/projectfinder/FoundProject.java, temp-name/src/main/java/org/jboss/bacon/tempname/impl/projectfinder/ProjectFinder.java, temp-name/src/test/java/org/jboss/bacon/tempname/impl/projectfinder/ProjectFinderTest.java, temp-name/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-100.json, temp-name/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-200.json, temp-name/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-300.json, temp-name/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-400.json, temp-name/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-500.json, temp-name/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-100.json, temp-name/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-200.json, temp-name/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-300.json, temp-name/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-400.json, temp-name/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-500.json
=> Add BuildConfiguration to FoundProject

guide/build-config.md
=> Document generic parameter option

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pom.xml
=> Upgrade quarkus version to 2.15.3

temp-name/src/main/java/org/jboss/bacon/tempname/impl/config/BuildConfigGeneratorConfig.java, temp-name/src/main/java/org/jboss/bacon/tempname/impl/config/DependencyResolutionConfig.java, temp-name/src/main/java/org/jboss/bacon/tempname/impl/dependencies/DependencyResolver.java, temp-name/src/main/java/org/jboss/bacon/tempname/impl/generator/BuildConfigGenerator.java
=> Autobuilder

experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DependencyResolutionConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] Add includeOptionalDependencies dep resolution option

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/projectfinder/ProjectFinder.java
=> Autobuilder fixes

experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/projectfinder/ProjectFinder.java
=> [AB] Imrpove logging and output

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/BifrostClient.java
=> [NCL-7080] Refactor CLI to read logs of completed builds from Bifrost

pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/BifrostClient.java
=> Improve bifrost client queries

guide/experimental.md
=> Fix spaces/tabs

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/RepoGenerationData.java, pig/src/test/java/org/jboss/pnc/bacon/config/ConfigReaderTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/config/RepoGenerationDataTest.java, pig/src/test/resources/build-config-custom-repo-generation.yaml
=> [NCLSUP-827] Fix parsing includeJavadoc

guide/build-config.md
=> Add documentation for new source strategy and repo option

experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] update to new domino 0.0.79 API

experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DependencyResolutionConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] Add recipeRepos dependencyResolutionConfig option

guide/build-config.md
=> Fix source generation parameter name in Doc

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/BuildFinderUtils.java, pom.xml
=> fix License generation and update PME + Build Finder

index.md
=> Specify supported jdk for bacon

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java
=> [AB) Remove manipulation.disable=true form copied BCs

guide/build-config.md
=> fix typo mavne

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/ArgumentTokenizer.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java, experimental/src/test/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGeneratorTest.java
=> [AB] Use DrJava's ArgumentTokenizer to properly filter Align params

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> [NCLSUP-858] fix repo generation for single bom

pom.xml
=> Upgrade to Domino 0.0.84 and Quarkus 2.16.6.Final

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/projectfinder/EnvironmentResolver.java
=> [AB] Upgrade deprecated environments based on the provided replacement

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
=> [NCLSUP-273] Fix pig ignoring description

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/StrategyConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListAlignmentStrategyCheck.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListAlignmentStrategyValidator.java
=> [Alignment 2.0] add option to specify strategies in buildConfig.yaml

experimental/src/main/java/org/jboss/bacon/experimental/DependencyGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/cli/DependencyGeneratorCommand.java
=> [AB] Add dependency-tree experimental command

experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] Log domino config on debug

experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] build domino config before use

experimental/src/main/java/org/jboss/bacon/experimental/DependencyGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/cli/DependencyGeneratorCommand.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] Add CLI parameter for including domino config

experimental/src/main/java/org/jboss/bacon/experimental/DependencyGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java
=> Improve Autobuilder UX

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
Depending on the source generation, we may download sources for the builds done as part of the group build in PiG + other sources as specified by the user.
Unfortunately we were modifying the global `builds` map that should only contain the builds done in a group build. This in turn, confused CPaaS into what builds were actually done.
This commit introduces a shallow copy of the builds map so that we modify this instead to add any additional builds to to download sources instead of modifying the global one.
=> [NCL-7258] Don't modify the builds map for source generation

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerationData.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
Jira: https://issues.redhat.com/browse/NCL-7989
Related PRs:
- https://github.com/project-ncl/bacon/pull/1076
- https://github.com/project-ncl/bacon/pull/1077
=> [NCL-7989] allow to exclude specific builds in sources generation

guide/build-config.md
Jira: https://issues.redhat.com/browse/NCL-7989
Related PRs:
- https://github.com/project-ncl/bacon/pull/1076
- https://github.com/project-ncl/bacon/pull/1077
=> [NCL-7989] add excludeSourceBuilds option for sources generation in guide/build-config.md

pig/src/main/resources/rh-license-exceptions.json, pig/src/main/resources/rh-license-names.json
=> Fixing Bocker: 3265 EPL

auth/pom.xml, cli/pom.xml, common/pom.xml, config/pom.xml, da/pom.xml, experimental/pom.xml, integration-tests/pom.xml, pig/pom.xml, pnc/pom.xml, pom.xml, test-common/pom.xml
=> Update to 2.6.0-SNAPSHOT version

auth/pom.xml, cli/pom.xml, common/pom.xml, config/pom.xml, da/pom.xml, experimental/pom.xml, integration-tests/pom.xml, pig/pom.xml, pnc/pom.xml, pom.xml, test-common/pom.xml
Reverts project-ncl/bacon#1083
=> Revert "Update to 2.6.0-SNAPSHOT version"

pig/src/main/resources/rh-license-exceptions.json
=> Additional licenses for rockdbjni

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/LicenseGenerationData.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> [NCL-8165] Allow to suppply license exception jsons as parameter

experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [AB] Redirect System.out from Domino calls to logger

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
=> [NCL-8087] Remove check for incompatible BCs

guide/build-config.md
This is a follow up to https://github.com/project-ncl/bacon/pull/1105
FYI @thescouser89 @jomrazek 
Thanks!
=> Documented BOM Maven repository generation strategy

pig/src/main/resources/rh-license-names.json
=> fix LGPL license metadata

eclipse-codeStyle.xml, pom.xml
=> Apply spotless on every run

DEVELOPING.md, cli/pom.xml, pom.xml
This also bumps Maven core dependencies to the latest 3.9.6 and maven-resolver to 1.9.18.
If this change is acceptable, this definitely should be mentioned in the Changelog (to be done)
FYI @jomrazek @janinko
=> Upgrade Java source and target versions to 17 and Quarkus dependencies to 3.8.1

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
Add some debugging info to the addDependency method.
=> Add debugging info

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java
=> Fix to return the prop with exceptionsPath and namesPath

pig/src/main/resources/rh-license-exceptions.json, pig/src/main/resources/rh-license-names.json
=> add license exceptions for io.opencensus and com.google.re2j artifacts

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java
While we re-work our PNC CLI code to regenerate the auth token before it expires, right now it just expires after 5 minutes. The workaround is that we'll just use an anonymous client that doesn't use an auth token and therefore there's no weird 401 error (we don't need authentication for GET anyways).
=> Use anonymous client for BuildInfoCollector

pom.xml
=> Update to latest pnc artifacts for 2.7.x

pom.xml
So that we can use Java 21 compiler
=> Update to lombok 1.8.32

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java, pom.xml
=> Activate spotless at compile phase

auth/src/main/java/org/jboss/pnc/bacon/auth/KeycloakClientImpl.java, auth/src/main/java/org/jboss/pnc/bacon/auth/model/Credential.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
=> [NCL-8487] Refresh access token as needed for Bacon

common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java, common/src/test/java/org/jboss/pnc/bacon/common/ObjectHelperTest.java, pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoBuilder.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
=> Hide download logs for repackage if not verbose

experimental/src/main/java/org/jboss/bacon/experimental/cli/DependencyGeneratorCommand.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pom.xml
=> Dep updates to fix CVEs

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/BomRepoGenerationSummary.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ResolvedGav.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java
=> Trim gav parsing and improve error reporting for BOM strategy

experimental/src/main/java/org/jboss/bacon/experimental/impl/config/BuildConfigGeneratorConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DefaultBuildConfigValues.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DependencyResolutionConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/projectfinder/ProjectFinder.java, experimental/src/test/java/org/jboss/bacon/experimental/impl/projectfinder/ProjectFinderTest.java, experimental/src/test/resources/wiremock/__files/body-pnc-rest-v2-build-configs-empty-page.json, experimental/src/test/resources/wiremock/mappings/mapping-pnc-rest-v2-build-configs-empty-page.json
=> Autobuilder changes

config/src/main/java/org/jboss/pnc/bacon/config/Config.java, integration-tests/src/test/resources/config/config.yaml
=> [NCL-7390] Warn user about wrong pnc url format

guide/build-config.md
This a little doc for https://github.com/project-ncl/bacon/pull/1192
=> Document nonManagedDependencies parameter of the BOM Maven repo gen strategy

common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java
Issue: [NCLSUP-1091](https://issues.redhat.com/browse/NCLSUP-1091)
=> [NCLSUP-1091] enable yaml LITERAL_BLOCK_STYLE

.gitignore, pom.xml
=> Update slf4j libraries and logback

cli/src/main/docker/Dockerfile
=> Remove the WORKDIR setting from the Dockerfile

cli/src/main/docker/Dockerfile
=> Install jq in the bacon cli image

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pom.xml
=> Update to PNC Rest Client 3.0.0

pom.xml
=> Update PNC dep to 3.0.3

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileUtils.java
=> Support symbolic links in delivered src zip

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
Fixes https://issues.redhat.com/browse/QUARKUS-4940
=> Exclude unwanted files from sources

pom.xml
=> Update build-driver to newest snapshot

cli/src/main/docker/Dockerfile
=> Add yq to bacon-cli container image

licenses-generator/src/main/java/org/jboss/pnc/bacon/licenses/LicensesFileManager.java
429 HTTP is : Too Many requests
=> [NCLSUP-1183] Retry on license download for 429 HTTP

pom.xml
This reverts https://github.com/project-ncl/bacon/pull/1322 as the CI in job/Devel/job/bacon/job/bacon-pull-request/541/console actually failed.
=> Revert logback version and use single version

pnc/src/main/java/org/jboss/pnc/bacon/pnc/DependencyAnalysisCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Pnc.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java
=> NCL-8072 / NCL-8073 Deliverable Analyzer

pig/src/main/resources/rh-license-exceptions.json
=> fix jfreechart license in rh-license-exceptions.json

pnc/src/main/java/org/jboss/pnc/bacon/pnc/DeliverableAnalysisCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Pnc.java
=> NCL8073 Fix naming

pig/src/main/resources/rh-license-exceptions.json, pig/src/main/resources/rh-license-names.json
pig license generator wasnt able to resolve license info for these artifact
=> Add exceptions for artifacts

pig/src/main/resources/rh-license-exceptions.json
=> Add license for org.jboss:jboss-transaction-spi and fix regular expression for some other licenses

licenses-generator/src/main/resources/rh-license-names.json
=> Update licence info for lgpl-2.1

licenses-generator/src/main/resources/rh-license-names.json
This reverts commit 0b2c837e845fc17a37bf1573faa9a038788e545a.
=> Revert "Update licence info for lgpl-2.1"

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
It checks that the response for the download of the source tar is HTTP status 200, otherwise it fails with a runtime exception that shows the reason and prevents us to untar an empty file.
=> [NCLSUP-1269] Throw an exception if we cannot download the source tar

pig/src/main/resources/rh-license-exceptions.json
=> rh-license-exceptions.json: use a single Apache License 2.0 name to avoid duplicated licenses files with the same content

pig/src/main/resources/rh-license-exceptions.json
=> rh-license-exceptions.json: standardize the lgpl-3.0 license name and urls

experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DependencyResolutionConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java, pom.xml
=> [AB]: Add option to specify maven settings.xml and migrate from deprecated API

index.md
Documentation for https://github.com/project-ncl/bacon/pull/1451
=> Document autocompletion

experimental/src/main/java/org/jboss/bacon/experimental/impl/config/DependencyResolutionConfig.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/dependencies/DependencyResolver.java
=> [NCL-9253] Fix settings xml parsing

pig/src/main/resources/rh-license-exceptions.json
=> rh-license-exceptions.json: update licenses version for rocksdbjni artifact

bacon_install.py
=> Fix github raw link in install script

docs/index.md
=> Update install docs
