pom.xml, src/main/resources/logback.xml
This commit adds slf4j / logback to the project. JBoss logging (used in
Weld) automatically detects it and use slf4j / logback as the backend
logging solutions instead of JDK logging.
Without slf4j, running a command starts Weld which outputs fairly
useless logs:
```
➜  cli git:(master) ✗ java -jar target/bacon.jar pig build
Jan 01, 2019 11:57:43 AM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.0.5 (Final)
Jan 01, 2019 11:57:43 AM org.jboss.weld.environment.deployment.discovery.DiscoveryStrategyFactory create
INFO: WELD-ENV-000020: Using jandex for bean discovery
Jan 01, 2019 11:57:43 AM org.jboss.weld.bootstrap.WeldStartup startContainer
INFO: WELD-000101: Transactional services not available. Injection of @Inject UserTransaction not available. Transactional …
```
=> Add slf4j / logback

src/main/java/org/jboss/pnc/bacon/App.java
Output when using the '--version' option should look like this:
```
➜  cli git:(use-version) ✗ java -jar target/bacon.jar --version
1.0-SNAPSHOT (a37aa79)
```
=> Set the version in picocli to the one in maven

src/main/java/org/jboss/pnc/bacon/App.java, src/main/java/org/jboss/pnc/bacon/cli/Pig.java, src/main/java/org/jboss/pnc/bacon/cli/Pnc.java, src/main/java/org/jboss/pnc/bacon/cli/SubCommandHelper.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/BrewPush.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Build.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/BuildConfiguration.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Environment.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GenerateTools.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GroupBuild.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/GroupBuildConfiguration.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Product.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductMilestone.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductRelease.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/ProductVersion.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Project.java, src/main/java/org/jboss/pnc/bacon/cli/pnc/Repository.java
When the cli is called with no option / subcommand, print the usage as
the default behaviour.
For example:
```
➜  cli git:(add-default-behaviour) ✗ java -jar target/bacon.jar
Usage: java -jar bacon.jar [-hV] [COMMAND]
-h, --help      Show this help message and exit.
-V, --version   Print version information and exit.
Commands:
pig
pnc
da
➜  cli git:(add-default-behaviour) ✗ java -jar target/bacon.jar pig
Usage: java -jar bacon.jar pig [-hV] [COMMAND]
-h, --help      Show this help message and exit.
-V, --version   Print version information and exit.
Commands:
build
configure
docs
javadocs
licenses
repo
scripts
shared-content
sources
addons
```
=> Default behaviour when command called with no opt

auth/pom.xml, auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java, auth/src/main/java/org/jboss/pnc/bacon/auth/KeycloakClientException.java, auth/src/main/java/org/jboss/pnc/bacon/auth/model/Credential.java, auth/src/main/java/org/jboss/pnc/bacon/auth/model/KeycloakResponse.java, auth/src/main/java/org/jboss/pnc/bacon/auth/spi/KeycloakClient.java, pom.xml
This commit adds support for authentication to Keycloak using direct
flow. We are also working on using official Keycloak libraries to get
authentication to work via authorization code flow (which is more secure)
It also adds an interface for authentication which can be used for both
direct flow, authorization code flow, and for any other kind of flow in
the future.
- Save the access token and the refresh token in a cache file somewhere
to re-use if still valid.
cc: @matejonnet @michalszynkiewicz @jbartece @geoand
=> [NCL-4338] Auth using direct flow for Keycloak

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, common/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/SubCommandHelper.java, da/pom.xml, da/src/main/java/org/jboss/bacon/da/Da.java, pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pnc/pom.xml, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPush.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Build.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfiguration.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Environment.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GenerateTools.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuild.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildConfiguration.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Pnc.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Product.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestone.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductRelease.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersion.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Project.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/Repository.java, pom.xml
The new output with aesh looks like this:
```
➜  cli git:(aesh-impl) ✗ java -jar cli/target/bacon.jar       
Usage: bacon.jar [<options>]
Bacon CLI
Options:
-h, --help     print help
-V, --version  print version
bacon.jar commands:
pnc  PNC sub-command
da  Dependency Analysis related commands
pig  PfG tool
➜  cli git:(aesh-impl) ✗ java -jar cli/target/bacon.jar pig 
13:08:40.885 [main] WARN  org.jboss.pnc.bacon.config.Config - Config file: config.yaml has no content
Usage: bacon.jar pig [<options>]
PfG tool
Options:
-h, --help     print help
-V, --version  print version
pig commands:
configure  Configure
build  Build
repo  GenerateRepository
licenses  GenerateLicenses
javadocs  GenerateJavadocs
sources  GenerateSources
shared-content  GenerateSharedContentAnalysis
docs  GenerateDocuments …
```
=> Replace picocli with aesh

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractNotImplementedCommand.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigurationCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GenerateToolsCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/RepositoryCli.java
This commit also introduces AbstractNotImplementedCommand, whose default
behaviour is to print 'Not Implemented yet!' for not-yet-implemented
commands to warn users.
=> GetSpecific, list for Project,Repository,BC,Environment

cli/src/main/resources/logback-test.xml
The logback.xml in koji-build-finder is 'erasing' our cli's logback.xml
in the final jar. To workaround this, this commit renames our
logback.xml to logback-test.xml, since this has higher priority compared
to logback.xml
https://logback.qos.ch/manual/configuration.html
=> Make our logback settings *the* logback setting

pnc/pom.xml, pom.xml
This is required to properly format ISO8601 strings into Instant
objects.
=> [NCL-4597] Include jackson-datatype-jsr310

common/src/main/java/org/jboss/pnc/bacon/common/Fail.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractNotImplementedCommand.java, config.yaml, config/pom.xml, config/src/main/java/org/jboss/pnc/bacon/config/KeycloakConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/PncConfig.java, config/src/main/java/org/jboss/pnc/bacon/config/Validate.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/OSCheck.java, pnc/pom.xml, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
The Keycloak authentication automatically kicks in when the config file
has the keycloak section in it.
The authentication is currently being done via the direct flow.
A helper method in `PncClientHelper#authRequired` is provided to *stop*
the application if it did not authenticate to Keycloak.
The format of the keycloak config is specified in the config.yaml
=> [NCL-4338] Add Keycloak authentication

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, config/src/main/java/org/jboss/pnc/bacon/config/Config.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductReleaseCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
This allows users to run '--help' or '--version' without having to have
a valid configuration file
This should resolve: https://github.com/project-ncl/cli/issues/38
=> Delay call to config until required

pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
The output looks something like this:
```
[DEBUG] - clientSecret is not specified in the config file! Assuming this is a regular user
[DEBUG] - Authenticating to keycloak
[DEBUG] - Getting token via username/password
[ERROR] - Credentials don't seem to be valid
```
=> [NCL-4338] Fail if credentials are not valid

pnc/src/main/java/org/jboss/pnc/bacon/pnc/AdminCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/AnnouncementBannerCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/MaintenanceModeCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
The commands can be found inside the top-level admin command
Activating the maintenance mode with the reason
```
➜  cli git:(ncl-5297) ✗ java -jar cli/target/bacon.jar pnc admin maintenance-mode activate "testing me"
[DEBUG] - clientSecret is not specified in the config file! Assuming this is a regular user
[DEBUG] - Authenticating to keycloak
[DEBUG] - Using cached credential details
```
The maintenance mode 'reason' is used to set the announcement banner.
Running any other command will print the announcement banner
```
➜  cli git:(ncl-5297) ✗ java -jar cli/target/bacon.jar pnc admin maintenance-mode status
[WARN ] - ***********************
[WARN ] - Announcement: testing me
[WARN ] - ***********************
PNC is in maintenance mode
testing me
```
When the maintenance mode is …
=> [NCL-5297] Add maintenance mode and announcement banner commands.

cli/src/main/resources/logback-test.xml, common/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java
This commit add the '-v' or '--verbose' flag to `AbstractCommand` to allow the
user to specify the desired verbosity of the output. The verbose flag
should therefore be available to all the commands.
All the log output is printed to stderr, as before. This is so that
users who want to consume the stdout output into a file (or pipe it)
doesn't also get the log data.
Example:
```
\# Piping stdout to /dev/null to hide output
$ java -jar cli/target/bacon.jar pnc product list > /dev/null
\# Verbose flag used
$ java -jar cli/target/bacon.jar pnc product list --verbose > /dev/null
[DEBUG] - Log level set to DEBUG
[INFO ] - Bootstrapping http engine with request retry handler...
[DEBUG] - Requesting: GET http://<url>/pnc-rest-new/rest-new/generic-setting/announcement-banner Headers: …
```
=> [NCL-5452] Allow user to specify verbosity

common/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractGetSpecificCommand.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractListCommand.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductReleaseCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java
Commit changes default output for commands with relevant info to yaml, using `-o/--jsonOutput `output could be changed to json format.
=> [NCL-5451] Allow user to specify format of output: YAML or JSON

auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java, auth/src/main/java/org/jboss/pnc/bacon/auth/model/CacheFile.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/VersionInfo.java, config/src/main/java/org/jboss/pnc/bacon/config/Config.java
Mainly made sure errors are logged and displayed without stacktrace for pnc commands, I also went through pig to be sure nothing is just printed out, didn't remove logging of stacktrace  (don't know if it can be helpful for user in pig, open to suggestions)
=> [NCL-5465] Edit error messages to more elegant and user friendly format

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java
Instead of the commands starting with 'get-', they now start with 'list-'
This affects the project 'list-build-configurations', 'list-builds', and
product-milestone 'list-performed-builds'
=> [NCL-5523] Name listy commands appropriately

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BrewPushCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/EnvironmentCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductMilestoneCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductReleaseCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProductVersionCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ProjectCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/ScmRepositoryCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/AnnouncementBannerCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/admin/MaintenanceModeCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/common/ClientCreator.java
This is done by getting rid of the duplicate 'getClient' and
'getClientAuthenticated' methods in the various Cli classes and
replacing it with the `ClientCreator` class which contains the logic.
It uses reflection to create a new instance of the Client and properly
caches the un-authenticated, and authenticated clients.
=> [NCL-5509] Fix Authentication broken in multicall commands

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java
Instead of showing a stacktrace, we should print a nice message that
warns the user that the wrong arguments were used when calling the CLI
Message is:
```
➜  cli git:(master) ✗ java -jar cli/target/bacon.jar pnc upgrade
[ERROR] - Wrong options: Command and/or sub-command is not valid!
```
=> Print a nice message when wrong arguments used

auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java, common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
The -c option is especifically for pig, whereas the '-p' option
is to specify the config folder for PNC.
=> Remove ambiguity between the -c and -p option in pig

config.yaml, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
Add check to make sure that the keycloak section in the configuration is
filled if we require authentication.
e.g when the Keycloak section is not specified in the configuration file
```
➜  bacon git:(fix-config) ✗ java -jar cli/target/bacon.jar pnc build start 100 -v -p ~/
[DEBUG] - Log level set to DEBUG
[DEBUG] - Config file set from flag to /home/dcheung//config.yaml
[ERROR] - Keycloak section is needed in the configuration file!
```
=> Fix eg config.yaml alignment for keycloak and check

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java
Native bash completion is not straight forward as it might have seem so I decided to use aesh console to simplify and add reliability to this issue.
Bacon usage can now be split into 2 cases
-bacon console (for comfort manual usage with completion of available commands)
when running bacon without arguments `java -jar bacon.jar` it starts bacon console where you can specify commands directly without running java -jar bacon.jar for every command.
-script usage (bacon how it functioned until now)
adding arguments to command will cause to not start bacon console and allow bacon to be still used as it was until now
possible improvements: loading config and profile for whole console session... ?
=> [NCL-5445] Add bash completion support for CLI 2.x

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java
If the default params are empty, storing the Pig Context throws an NPE
as we are trying to parse a null url. This commit will only parse the
url if not-null.
Fixes #218
=> Properly store pig context if default params empty

cli/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/cli/VersionInfo.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/license/LicenseGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/resources/license-generator.properties, pig/src/main/resources/release.sh, pig/src/main/resources/uploadToCandidates.sh, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java
This is done by:
- replacing maven-assembly-plugin to maven-shade-plugin, which does some
magic to make plexus container happy (cli/pom.xml)
- Make VersionInfo read from main manifest attribute to get version info
- Update license-generator.properties to properly do template
substitution
- Check license error from xml file, not xml folder
(LicenseGenerator.java)
=> Fix license generation and other bugs

pom.xml
This resolves issues described in #299
Internal certs are only installed in default JDK
=> Switch back to Java 8

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/SleepUtils.java
Since some apps consume our stdout for data, we should print the dot
progress to indicate something is in progress in stderr instead of
stdout.
Partially Fixes #289
=> Print progress dot in stderr

pig/src/main/resources/README.ftl
PiG generates a README.html file from the README.ftl template file.
Since we now specifies the scheme of PNC Orch's link in our config, the
generated README.html has the scheme specified twice:
```
http://http://orch-stage.DOMAIN/pnc-web/#/build-records/14160
```
This commit fixes this. Thanks to @goldmann for noticing and reporting
this ♥
=> [#304] Fix the addition of double scheme in pig README

.codecov.yml
It's triggering weird errors that we'll investigate later
=> Remove patch in codecov.yml

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java
The config dir check was eagerly being run before the check for help /
version flags. This commit fixes it
=> Properly use the '-h' in pig * commands

pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildConfigCli.java
Properly update the build config params without erasing the
non-specified ones in the update options.
=> [NCL-5951] Properly update the build config params

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java
Hi guys. This should fix NCL-5943(#326) but as I am not familiar with PIG I fear this specific solution($1) might have side-effects which I cannot predict. 
Other possible solution($2) is to handle this case just before throwing an exception here:
https://github.com/project-ncl/bacon/blob/869832e483c9fd9564b5474054394c92e38a71c8/pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java#L89
Should I go with $1, try to improve $1 or go with $2
=> [NCL-5943] fix NoSuccessfulBuildException on unchanged BuildConfig when a temporary build is not rebuilt after a regular build

cli/src/main/resources/logback-test.xml
The default value is false. There is no need to change it since it's not required on modern platforms and it breaks the tests. And it won't work unless you also have jansi on the classpath.
=> Remove withJansi from logback-test.xml

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
Don't use buildConfig::matchesRepository in the check as PNC's match endpoint
should be always returning single matching SCM Repository if it exists.
=> Fix checking for existing SCM Repository in pig

bacon_install.py
```
~/projects/work/bacon ncl-5996 !1 ❯ python3 bacon_install.py update
Downloading: https://repo.maven.org/maven2/org/jboss/pnc/bacon/cli/maven-metadata.xml
Something wrong happened while downloading the link: https://repo.maven.org/maven2/org/jboss/pnc/bacon/cli/maven-metadata.xml
~/pr/work/bacon ncl-5996 !1 ❯ echo $?                                       ✘ 1
1
```
Thanks to @goldmann for reporting this issue! :)
=> [NCL-5996] Return non-zero return code if failure

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java
'overrideRequired' is used when you want to skip validation of required
Options or Arguments. This is typically useful for the '-h / --help' or
'-v /--version' flags, where we don't need to validate the input further
and we'll just print the help and version output respectively.
However this parameter is not useful for most other options. This commit
removes that parameter from options that shouldn't use it.
This also fixes the issue we had with 'pig run' where there were no
validation if the 'configDir' was passed in our input, which was caused
because the options had the 'overrideRequired=true' flag set.
Special thanks to @stalep for explaining to me the meaning of this
parameter in https://github.com/aeshell/aesh/issues/322
=> Remove overrideRequired from some options

pnc/src/main/java/org/jboss/pnc/bacon/pnc/Pnc.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/WhoAmICli.java
This is done to implement the old pnc-cli 1.x 'get-logged-user'
=> [NCL-5991] Add pnc whoami command

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java
Bacon/PiG runs a check to see if the commit of the branch has already
been built in PNC.
Unfortunately during this check an InputStream may not be closed
properly which causes the app to just hang.
This commit fixes it by always closing the InputStream
=> [NCLSUP-109] Stop make bacon stuck when checking branch

common/src/main/java/org/jboss/pnc/bacon/common/cli/AbstractCommand.java
I am not sure if you wanted an extra newline there to begin with, but try letting shell handle `writeln()` in case it is system-dependent. If we want another newline, we can try `shell.writeln("").`
=> Remove hardcoded line separator from Shell.writeln

cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/AbstractTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigTest.java, integration-tests/src/test/java/org/jboss/pnc/bacon/test/pnc/ProductTest.java, pig/src/test/java/org/jboss/pnc/bacon/config/ConfigReaderTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/documents/sharedcontent/da/DADaoTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/indy/IndyTest.java, pnc/src/test/java/org/jboss/pnc/bacon/pnc/ProductReleaseCliTest.java, pnc/src/test/java/org/jboss/pnc/bacon/pnc/common/ParameterCheckerTest.java
JUnit 4 forced test classes and methods to be public. JUnit 5 changed this. See also <https://github.com/junit-team/junit5/issues/679> where they made the change to their own codebase. This is a minor PR, but it adds some consistency (some tests were using this and some weren't).
=> Make test classes and methods package-private as per JUnit 5

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java
In a previous commit, we didn't download logs if the builds were
successful because the logs would be printed in the stdout and would be
way too long.
However this broke addons that rely on the logs. This commit reverts the
changes of the previous commit, and also doesn't print the logs
(successful or not) to the stdout.
The addons broken are: MicroProfileSmallRyeCommunityDepAnalyzer.java and
RuntimeDependenciesAnalyzer.java
=> [NCL-6018] Download logs even when build successful

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java
Split log lines across multiple items to fix NotYetAlignedFromDependencyTree.
=> [NCL-6018] Split log lines across multiple items

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/GitRepoInspector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java
The check assumed that the 'scmRevision' in the build information would
be a tag name. Instead it is the commit id.
This commit fixes it by grabbing the scmTag information instead which
contains the real tag name.
It also treats the 'branch' as either a ref (pointer to a commit), or
the commit itself. This should handle the corner case where the full commit
id is specified in the build-config.yaml
Optionals are also now used to better handle the case where the
information is not available
=> [NCLSUP-119] Fix check for isBranchModified

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
If the repository generation is ignored, the checksum data is never
populated. In that scenario, we shouldn't generate the nvr list during
the release phase since we don't have the required information.
=> [NCL-6037] Only generate nvr list when possible

bacon_install.py
When downloading artifacts from repositories.jboss.org, it sometimes
fails because the specific server we are hitting on
repositories.jboss.org does not have the content yet, and returns 404.
The retries is an attempt to workaround this by retrying to download the
artifact up to 7 times until we give up.
=> Add retries when downloading links on bacon_install.py

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java
This came from an upstream picocli example, which I have fixed upstream, see https://github.com/remkop/picocli/issues/1168 and https://github.com/remkop/picocli/pull/1169.
=> Close Terminal in App

cli/pom.xml, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java
It's OK if you still prefer the other way, but I thought I'd try a more minimal PR for AssertJ.
The advantage is more meaningful messages on test failures. For `assertEquals()` there is really no advantage to changing that, so I left `assertEquals()` and replaced:
- `assertTrue(text.contains())` with `assertThat(text).contains()`
- `assertFalse(text.contains())` with `assertThat(text).doesNotContain()`
- `assertEquals(StringUtils.countMatches(text, str), 1)` with `assertThat(text).containsOnlyOnce(str)`
=> Use assertj for testing strings for better failure messages

common/pom.xml, common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java, common/src/test/java/org/jboss/pnc/bacon/common/ObjectHelperTest.java
Replace manual tapping of System.out with tapSystemOut() in test
=> NCL-5986: Configure YAML to use system line feeds to match println()

pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilderTest.java, pom.xml
Due to internal logic in PNC-Orch, a group build gets updated in the
database just before the final build in the group build is done. This
may cause the scenario where during a time window, the group build state
is successful, but there's still 1 build in the group build still in
running state.
The situation is even worse if the group build ends in state
'NO_REBUILD_REQUIRED'. Before the builds even have a chance to be
scheduled, the group build is already marked as 'NO_REBUILD_REQUIRED'
beforehand. Then when we get the list of builds, they may still be in
status RUNNING. This is dangerous because then the final artifact list
may be empty, and in the case of NO_REBUILD_REQUIRED, we'll never get
the original successul build.
To avoid these scenarios, we also check if all the builds in a …
=> [NCL-6044] Check if all builds in final state when group build done 

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java
=> [NCL-6075] Bacon jsonOutput flag went missing

cli/pom.xml, cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, pom.xml
This explicitly enables tailtip support for the console interface. To do that I have had to inline a lot of picocli-jline3 support until https://github.com/remkop/picocli/issues/1175 is fixed (found during discussions on https://github.com/jline/jline3/issues/571 ).
If this is ok , I'll add a separate internal tracker to remove the override code (the second commit) once picocli 4.6 is out.
=> Enable tailtip widget by default by explicitly overriding picicli jline3

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/BuildInfoCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java
Since the build log is not stored in the context.json due to size, that
causes some issues.
1. If a pig command depends on the build log and it is not present, this
will stop the command from working. (e.g for `pig addons`)
It's also better to only get the build logs if necessary since they are
huge and take a lot of space. The build logs are cached within the same
pig command, but if you run multiple pig commands, the build logs will
be loaded from the PNC server again.
=> [NCL-6060] Get the build log on demand

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/javadoc/JavadocManager.java
This matches the same logic as for license generation
=> Set default javadoc generation to IGNORE

config/pom.xml, config/src/main/java/org/jboss/pnc/bacon/config/Validate.java, integration-tests/src/test/resources/config/build-config.yaml, pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/Flow.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/Output.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/ProductConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/GenerationDataCheck.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/GenerationDataValidator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigCheck.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigValidator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/GenerationDataCheckTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/ListBuildConfigCheckTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/validation/PigConfigurationValidationTest.java, pig/src/test/resources/build-config-UnknownVar.yaml, pig/src/test/resources/build-config-VarUsage.yaml, pom.xml
This uses Hibernate Validator and Java EE Bean validation to accomplish
this.
Two custom bean validators are written to validate Build Configs and the
flow generation when set to 'DOWNLOAD'.
e.g
```
~/projects/work/bacon ncl-5982 ❯ java -jar cli/target/bacon.jar pig build nightly                                                           8s
[INFO ] - the configuration has been changed since the last run, using clean pig context
[INFO ] - HV000001: Hibernate Validator 2.1.2-SNAPSHOT
[ERROR] - Errors while validating the build-config.yaml:
Field: builds[0].project must not be blank
Field: product.name must not be blank
```
=> [NCL-5982] Add validation to build-config.yaml

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
Since `executeBrewPush` invocation disconnects the websocket client, we
shouldn't re-use the AdvancedBuildClient for further brew pushes since
the websocker listener is disconnected.
This commit instead creates a new client for every push to workaround
the limitation.
=> Use `executeBrewPush` only once

pom.xml
This reverts commit fe35147bd512fef004b586e5e159aec29236f532.
It breaks stuff with our port set to 'null' from the PNC Client
=> Revert "Bump httpclient from 4.5.12 to 4.5.13"

cli/src/main/java/org/codehaus/plexus/logging/console/ConsoleLogger.java
Massive hack to override the default plexus logging implementation,
ConsoleLogger, is adapted to Slf4j, rather than the actual
implementation that just prints to stdout
All credit for this genius idea goes to Mr David Walluck (@dwalluck)
Our license generator (snowdrop licenses) uses Maven core under the hood
for its business. Unfortunately, the DefaultProjectBuilder from Maven
core uses Plexus Logger, with default implementation ConsoleLogger (I
couldn't find a way to tell maven to use a different implementation).
The ConsoleLogger implementation is rather primitive and just prints to
stdout.
This is not OK because we'd like all of our logging to be controlled by
slf4j. More specifically, right now we want all of our logs to go to
stderr, not stdout.
This re-implementation replaces the …
=> [NCL-6155] Provide alternative impl of ConsoleLogger

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
cc @michalszynkiewicz 
this much change only should also work for `quarkus-bom`
=> Add support for quarkus-bom.json devtools for parent build only in Quarkus Community dep analyser

guide/configuration.md
Thanks to @riprasad for pointing out this mistake in our docs.
=> Remove the 'password' field in the configuration doc

integration-tests/src/test/java/org/jboss/pnc/bacon/test/pig/PigFunctionalTest.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/test/java/org/jboss/pnc/bacon/config/ConfigReaderTest.java
This is done by passing the parameter:
```
bacon pig run .. \
-eVariable1=Value1 \
-e variable2=value2 \
--env=variable3=value3
```
=> [NCLSUP-171] Set vars in PiG from command line

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/HashUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/HashUtilsTest.java, pig/src/test/resources/hash/copy-with-file-to-be-ignored/file1.txt, pig/src/test/resources/hash/copy-with-file-to-be-ignored/file2.txt, pig/src/test/resources/hash/copy-with-file-to-be-ignored/ignore-me
When generating the hash of the directory config to determine whether
the pig-context.json should be invalidated or not, the hash should
ignore the files 'bacon/pig-context.json' and the contents inside the
'target' folder.
This is to handle a special case where the user may run the `bacon pig`
command using path '.', in which case the 2 files mentioned above will
be created inside the directory config.
Since those 2 files change content all the time, it causes the hash of
the directory to be always different between `bacon pig` runs and
wrongly invalidates the existing pig-context.json because it wrongly
assumes that the *real* content of the directory config has changed.
=> [NCLSUP-174] Ignore pig-context and target folder

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
cc @michalszynkiewicz  @paulgallagher75 
Generated devtoolsJarName is changed due to changes in upstream 
https://github.com/quarkusio/quarkus/blob/8e3fdd379c41f280049ec83e9f273e22643df534/bom/application/pom.xml#L218
Due to which I have make changes in QuarkusCommunityDepAnalyser
=> Change devtoolsJarName in QuarkusCommunityDepAnalyser

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ExternalArtifactDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
Only try once to download source artifacts as they can be missing (and from our repo there are a lot of missing source artifacts) which can cause the repo build time to be considerably larger.
=> Stop source artifact downloads from retrying

cli/pom.xml, cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, pig/pom.xml, pom.xml
Special thanks to @matejonnet for figuring out how to resolve the issue with PME's uber jar having an older version of picocli overriding what we set in our pom.xml (use the minimal jar)
Special thanks to @rnc for submitting the changes/fixes to upstream picocli, and providing instructions on how to clean up the code once the fixes are in a picocli release.
=> [NCL-6080] Cleanup with picocli 4.6 changes

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ExternalArtifactDownloader.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java
When we get HTTP response 404 from our HTTP client, don't do further
retries in the hopes that the 404 changes to a 200 status.
CC: @AntStephenson
=> [MMENG-1127] Trust a 404 and don't retry

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/RepoGenerationData.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
Add excludedSourceBuilds list field to ignore specified projects in the BUILD_GROUP repository generation strategy
Signed-off-by: Alberto Morales Pérez <almorale@redhat.com>
Documented in: https://github.com/project-ncl/bacon/pull/618
=> Add excludedSourceBuilds to BUILD_GROUP strategy

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusCommunityDepAnalyzer.java
@michalszynkiewicz @harshmadhani 
this PR is to fix the incompatibility of openshift and s2i container-image extension,
these two extension cannot work together
=> update extension filter list to fix incompatibilty of openshift vs s2i

pig/src/main/resources/rh-license-exceptions.json
Removing licenses which contained invalid name "Lesser General Public License v3.0 or later". As the same artifacts are present under correct license names in the json file, I removed the license instead of just updating the license name
=> Removing artifacts which contained invalid license name

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/indy/Indy.java
The temporary builds group consists of only the hosted repo so it doesn't make sense not to use the hosted repo directly.
=> [NCLSUP-298] use temporary hosted repo instead of a group

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupBuildCli.java
=> [NCL-6464] Deprecate Timestamped teporary builds option in Bacon

guide/pig.md
Hi @thescouser89 @rnc,
Here is the PR updating the doc with the newly added add-on  `Vertx Artifact Finder` #648  :)
I previewed the changes using ` Jekyll ` and it is looking like this -
=> Adding details of vertx addon in the doc

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/main/resources/logback-test.xml, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java
When running bacon in specific environment where the logs are piped into
files, the ANSI color commands show up in those logs and make them hard
to read.
This commit adds the --no-color flag to disable color/ANSI output in
picocli output. The user can also disable coloring by setting the
'NO_COLOR' environment variable with any value (https://no-color.org/).
We also remove the '%highlight' in the logback file to disable coloring
of the message level printed in stderr for logging.
=> [NCLSUP-306] Disable CLI output with --no-color flag

cli/src/main/java/org/jboss/pnc/bacon/cli/App.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, common/src/main/java/org/jboss/pnc/bacon/common/ObjectHelper.java
When the quiet option is enabled, the logging level is set to 'ERROR' (no
logs, unless critical will be printed) and any YAML/JSON printed at the end will also not
be printed
=> [NCL-6058] Add quiet option (-q)

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGenerator.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/rhba/OfflineManifestGeneratorTest.java
Use excludeSourceBuilds repo config to generate offliner manifest when repo strategy is set to BUILD_GROUP or IGNORE
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
=> BXMSPROD-1300 - use excludeSourceBuilds to generate offliner manifest

auth/pom.xml, auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java, pom.xml
The first commit ports from the old Unirest 1.x to Unirest 3.11.10, which comes with package name changes and a different way to configure the object mapper. Overall, Unirest 3.11.10 has a simpler design, which I like.
The second commit attempts to solve NCLSUP-425, which is to add retries to the Keycloak client. We have retries when reaching PNC-Orch, and retries when downloading from Indy, so there should also be a retry for the Keyclaok client! :) The retries however should help us resolve some instability that we've been seeing when reaching the SSO server lately.
=> [NCLSUP-425] Add retries for Keycloak client

pig/src/main/resources/rh-license-exceptions.json
Added license for com.github.luben:zstd-jni
=> Added license for zstd-jni

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigExport.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/mapping/BuildConfigMapping.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/mapping/BuildConfigMappingTest.java
This commit adds a new command to export a build-config into a YAML
output suitable to be added into PiG's build-config.yaml format.
Usage:
```
$ bacon pig export build-config <build-config-id>
---
name: "TC37-memory-allocation"
project: "TC37"
buildScript: "mvn deploy"
scmUrl: "https://github.com/michalszynkiewicz/empty.git"
scmRevision: "master"
systemImageId: "builder-rhel-7-j8-mvn3.6.0:1.0.4"
buildPodMemory: 5.0
brewPullActive: false
buildType: "MVN"
```
Doc PR is: #831
=> [NCL-6714] Export a build-config into PiG format

bacon_install.py
We should stop using it because the temp folder is not cleaned up after
the method is called. It is replaced with:
```
with tempfile.TemporaryDirectory() as temp_folder:
```
since cleanup of the temp folder happens once we exit the 'with' clause.
=> [NCL-6816] Stop using tempfile.mkdtemp in bacon_install.py

bacon_test.py, cli/pom.xml
The bacon_test.py is run on the cli module test phase. If the tests
fail, the compilation will also fail.
bacon_test.py is used to test the bacon install script.
```
[INFO] --- exec-maven-plugin:3.0.0:exec (python-test) @ cli ---
.F...
======================================================================
FAIL: test_bacon_install_with_version (bacon_test.TestBacon)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/home/dcheung/projects/work/bacon/bacon_test.py", line 109, in test_bacon_install_with_version
self.assertTrue(False)
AssertionError: False is not true
----------------------------------------------------------------------
Ran 5 tests in 30.782s
FAILED (failures=1)
Downloading: …
```
=> [NCLSUP-470] Add bacon_test.py

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
The same log is printed in the `build` method, which the `run` method calls.
=> Remove unecessary temporary build log

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/GroupConfigCli.java
Bacon likes to add the URL information of PNC elements inside brackets.
e.g "here (https://hello.com)"
It looks from our PNC logs that users copy the URL by hand and
unfortunately also copies the end of the bracket.
PNC then gets requests like:
- https://hello.com)
which confuses it. To reduce those kinds of errors, this commit adds an
extra space with the closing bracket to help the user not copy that kind
of error.
The output will then become:
- "here ( https://hello.com )"
=> [NCLSUP-491] Reduce confusion on pnc output for Url

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/ResolveOnlyRepositoryTest.java
When generating the maven repository, the user can now specify if she wants a failed source jar download to terminate the generation or not (default).
The flag option is: `--strictDownloadSource`. It is by default switched off.
The flag is added to command:
- `bacon pig run`
- `bacon pig maven`
=> [NCL-5973] Add option to be strict for source jars

auth/pom.xml, auth/src/main/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImpl.java, auth/src/test/java/org/jboss/pnc/bacon/auth/DirectKeycloakClientImplTest.java
Example without this commit:
```
[root@ab92857abab7 ~]# bacon pnc whoami
Enter your password:
[INFO ] - Having difficulty reaching https://secure-sso-newcastle-devel.psi.redhat.com/auth/realms/pncredhat/protocol/openid-connect/token. Retrying again...
[ERROR] - Keycloak authentication failed!, Error: org.jboss.pnc.bacon.auth.KeycloakClientException: kong.unirest.UnirestException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
The above command took a while to finish due to retries.
Example with this commit:
```
[root@ab92857abab7 ~]# java -jar /tmp/bacon.jar pnc whoami
Enter your password:
[ERROR] - Keycloak authentication failed!, Error: …
```
=> [NCLSUP-475] Don't retry when keycloak error is missing certificate

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/PigContext.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/PigConfiguration.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/PigContextTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/config/PigConfigurationTest.java, pig/src/test/resources/build-config.yaml
In NCL-5981, the user would like to provide a suffix for the
deliverables files and folder inside the zips.
For example: <product>-<version>-<suffix>-maven-repository.zip
This commit adds an additional optional field in the build-config.yaml named
'outputSuffix' that when specified, will be used as the suffix.
Example:
```
outputSuffix: picard
```
=> [NCL-5981] Add ability to provide a suffix for deliverables

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/config/BuildConfig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/mapping/BuildConfigMapping.java
Add ability to set generic parameters to build configuration not just predefined ones:
=> [NCL-6936] add option to set generic parameter

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java
https://project-ncl.github.io/bacon/guide/build-config.html#maven-repository-generation G:A:V is required but we're testing if at least 2 things are present, creating out of bounds error when user wrongly formatted file
=> Fix check for correct gav formatting

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtilsTest.java
The `excludeArtifacts` in the maven repository section for PiG works for
most maven repository generation except for RESOLVE_ONLY. This commit
adds the ability to use `excludeArtifacts` with RESOLVE_ONLY
The implementation works by first generating the final maven repository
from the bom specified, then deleting the artifacts in
`excludeArtifacts` from that maven repository.
The artifacts are specified in "Maven Identifier" format (aka
`<group-id>:<artifact-id>:<packaging>:<version>`). We convert that Maven
identifier into a filesystem path inside the maven repository folder and
delete it. Regexes are supported.
The other option was to generate the maven repository with the excluded
artifacts specified as exclusions. But I couldn't find any way to do
that using the Maven Resolver object.
=> Make excludeArtifacts for resolve only resolution

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/camel/RuntimeDependenciesToAlignTree.java
Move build to source statistics to a separate logging file, change file name of  dependencies to align to something more generic
=> Move build to source statistics to their own log, change file name of  dependencies to align to something more generic

pom.xml
licenses-generator uses org.jenkins-ci.lib:lib-jenkins-maven-embedder dependency which I would call obsolete, if there is no other suggestion how to solve this we need to dedicate time to upgrade licenses generator to use maven-embedder from apache or not upgrade above mvn 3.6.x as there is breaking change in ArtifactRepository (I believe)
=> Remove maven-embedder to fix dependency issue for licenses generator

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/camel/RuntimeDependenciesToAlignTree.java
Adding project logs if 
printProjectLogs: true 
is set within the configuration.    Will add a PR to document it.
=> Add project logs

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
This is needed to properly set the full version of the product.
Otherwise Bacon PiG fails later with the full version not being set.
This is thanks to a bug report from @lbossis !
=> [NCLSUP-624] Run `beforeCommand` for pig run command

pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/PostBuildScanService.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/ScanServiceDTO.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/pssaas/AddAuthHeadersRequestFilter.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/pssaas/RedirectAndLog.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/pssaas/ScanHelper.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/pssaas/ScanInterface.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/MockScanServiceTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/ScanServiceDTOTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/scanservice/ValidationTest.java, pom.xml
* [ x] Have you added unit tests for your change?
* 
This PiG addon allows the use of the CPaaS Product Security Scan as a Service, by default this addon, once configured, will send pnc builds in the context of the current pig build-config.yaml to the service which will then checkout and scan the code.
Usage and documentation are a WIP
=> This PiG addon allows the use of the CPaaS Product Security Scan as a Service

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtilsTest.java
Some build-config.yaml use this style for exclude artifacts:
```
.*:.*:war:.*
```
In Bacon, we do 2 rounds of filtering out the excluded artifacts. The
first round tries to match the excludeArtifacts with an artifact's GAPV
(group-id artifact-id packaging version).
The second round scans through the generated maven repository folder to
exclude files which have a path of format:
```
<group id>/<artifact id>/<version>/<artifact id>-<version>.war
```
In the example used above, the path to exclude becomes:
```
.*/.*/.*/.*-.*.war
```
Unfortunately this path to exclude matches with paths like:
```
org/kie/server/kie-server-wars/1.2.3.Final/kie-server-wars-1.2.3.Final.pom
```
even though the original intension is to match any file with extension 'war'.
The fix for this is to refine the excluded …
=> [NCLSUP-679] Bacon is excluding too many artifacts

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtilsTest.java
Some build-config.yaml use this style for exclude artifacts:
```
.*:.*:war:.*
```
In Bacon, we do 2 rounds of filtering out the excluded artifacts. The
first round tries to match the excludeArtifacts with an artifact's GAPV
(group-id artifact-id packaging version).
The second round scans through the generated maven repository folder to
exclude files which have a path of format:
```
<group id>/<artifact id>/<version>/<artifact id>-<version>.war
```
In the example used above, the path to exclude becomes:
```
.*/.*/.*/.*-.*.war
```
Unfortunately this path to exclude matches with paths like:
```
org/kie/server/kie-server-wars/1.2.3.Final/kie-server-wars-1.2.3.Final.pom
```
even though the original intension is to match any file with extension 'war'.
The fix for this is to refine the excluded …
=> [v2.2][NCLSUP-679] Bacon is excluding too many artifacts

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/FindTransitiveDuplicateArtifactsInDepTree.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/SaveBuildLogsLocally.java
saveBuildLogsLocally is a simple addon that saves the PNC build logs locally in the extras directory, very useful when you are building multiple build configs and need to do analyses on the text output of the build
findTransitiveDuplicateArtifactsInDepTree is an addon that uses the output from dependency:tree in the PNC build log and the list of duplicates from the maven repo zip to produce a report of where the entry points in the builds are for these duplicates, this makes it easier to track down and remove them
=> 2 new vertx addons

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java
Reverts project-ncl/bacon#965
redirect to /dev/null solves the problem so not needed `> /dev/null`
=> Revert "added --skipJsonOutput which if set turns off all the JSON output at …"

pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java
For some reason, picocli sets the array that contains the skippedAddon
as size 1 with content `['']` if there are no skippedAddon specified in
the CLI.
We need to add a blank string check to filter out those blank string and
ignore them
=> Ignore blank skippedAddon

cli/src/main/resources/logback.xml
When running on Java 11, Netty prints a scary *debug* message about not
being able to access the Unsafe APIs. This is normal and just printed as
a debug, but it looks like an error message.
This commit adjusts our logging to only print Netty error messages
instead.
Sources:
- https://stackoverflow.com/questions/64043706/java-lang-illegalaccessexception-class-io-netty-util-internal-platformdependent
- https://github.com/netty/netty/issues/7817#issuecomment-377497310
```
It's not an error, it's a debug message with a stacktrace, change your logger level to something else apart from debug eg. info or warn.
```
=> [NCL-7272] Hide netty debug message about using Unsafe

pnc/src/main/java/org/jboss/pnc/bacon/pnc/ArtifactCli.java
It's throwing iterator error when result is empty. Better solution didn't come to my mind, open to suggestions.
=> Fix get-gav error when there is no result found

pig/src/main/resources/rh-license-exceptions.json
Update the license exception for com.github.luben:zstd-jni to be regex based
=> Update the license exception for zstd-jni to be regex based

pig/src/main/java/org/jboss/pnc/bacon/pig/PigExport.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/mapping/BuildConfigMapping.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/mapping/BuildConfigMappingTest.java
--revision to select build config revision to export --environment-by-name to export with environmentName instead of environmentImageID
--rename to set the name of the exported build config
=> Add new options to pig export build-config

guide/build-config.md
This change is a follow up to https://github.com/project-ncl/bacon/pull/1005 that introduced `excludeTransitive` paremeter.
=> Documented excludeTransitive Maven repo generation parameter

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/GAVTest.java
- Add tests for GAV(String path) constructor and toGapvc() method
- Fix issue in GAV(String path) constructor which didn't handle packaging with a dot and didn't setup the classifier
- Fix issue in toGapvc() method which returned classifier null when it doesn't exist instead of dropping it from the String
=> Add tests for methods in GAV class

pom.xml
* 0.0.79 includes a critical fix when sorting project releases for the build. It is now taking into account *only* the direct dependencies of the artifacts as their appear in their POMs, instead of also those that appear as their direct dependencies in the dependency trees generated for the root project artifacts;
* Quarkus resolver 2.16.4.Final is what Domino is currently using.
=> Upgrade to Domino 0.0.79 and Quarkus 2.16.4.Final

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java, experimental/src/main/java/org/jboss/bacon/experimental/impl/projectfinder/ProjectFinder.java
Also adds a message to builds script from what build config revision was a generated build config copied from.
=> [AB] Fix detecting exact match for -redhat versions

pom.xml
Fixes Domino Gradle plugin dependency resolution when analyzing Gradle projects, among other things.
FYI @janinko
=> Upgrade to Domino 0.0.92 and Quarkus 2.16.7.Final

auth/pom.xml, auth/src/main/java/org/jboss/pnc/bacon/auth/KeycloakClientImpl.java, auth/src/main/java/org/jboss/pnc/bacon/auth/model/Credential.java, auth/src/test/java/org/jboss/pnc/bacon/auth/KeycloakClientImplTest.java, cli/src/test/java/org/jboss/pnc/bacon/cli/AppTest.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java, pom.xml
Firstly I created new client but by the point I got service account working it was either reusing existing logic or being too complicated so I threw it away and reused old stuff for service accounts and just used different client to redirect user auth to keycloak.
=> Rework bacon to redirect auth to SSO and not deal with passwords

pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/quarkus/QuarkusPostBuildAnalyzerTest.java
There is a lot of noise after running this test, this cleanup will remove files created by the test.
=> Clean files created during testruns

pig/src/main/resources/rh-license-names.json
1. Eclipse Distribution License 2.0 doesen't even exist
2. There are some inconsistencies in aliases.
=> fix inconsistencies in licenses metadata 

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncEntitiesImporter.java
If BC was in a product (or was in no product), then adding them to different one would - in some cases - thow an exception. We need to discuss more options for BC sharing between products, but in the meantime, we are removing this check.
=> [NCL-8087] Remove check for BC "stealing"

pig/src/main/resources/rh-license-exceptions.json
Add a license exception for oss-parent (one of the Red Hat versions is missing the license).
=> Update license exception for oss-parent

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
this was failing for existing file when user used mutliple versions built by same build configuration = oss-parent-50-redhat-9 and oss-parent-50-redhat-7
=> Make source download name more unique

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java
When waiting for a group build to finish in `PncBuilder`, get a new anonymous GroupBuildClient to know the state of the group build.
If we use the regular groupBuildClient, its access token might have already expired and we'll get a 401 error eventually.
=> No auth while waiting for build to finish

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilder.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuilderTest.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/client/PncClientHelper.java
If we use the regular group client for a long time, the token it holds might expire after a period of time. When we send the expired token to PNC, it fails with HTTP 401 error.
This change:
- uses anonymous group client so that we don't send any token if there's no need to
- adds the bearerSupplier in PncClientHelper so that we can use it to renew our auth token if necessary.
=> Fix 401 error: use anonymous group client for get

experimental/src/main/java/org/jboss/bacon/experimental/impl/generator/BuildConfigGenerator.java
Minor label change - "genearated" -> "generated"
=> Fix generated label typo

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/sources/SourcesGenerator.java
Update the source generation so directory naming is more consistent, because its derived from the build config there are inconsistencies in how people name them. For example, one directory is simply called `2.2.0` without any reference to the groupId or artifactId.
This PR updates the naming to be derived from the BREW_BUILD_NAME and BREW_BUILD_VERSION which to my knowledge should be available as its automatically set, and I have double checked numerous builds including some gradle ones and it was, but if they aren't set it will leave them as is.
=> Update source generation to use consistent format for directory structure

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoDescriptor.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/GAVTest.java
1. Remove `maven-metadata.xml` from the constant that represents checksum extensions `RepoDescriptor.CHECKSUM_EXTENSIONS` (while it's used by some methods to identify checksum files, in other places it appears to be misused to filter out non-artifact files)
2. Fixed artifact filtering in `RepoDescriptor.listGavs(File dir)`, it doesn't filter out `_remote.repositories` as a non-artifact file (since it relied on `RepoDescriptor.CHECKSUM_EXTENSIONS`) which results in parsing it as
```
System.out.println(new GAV("org/jboss/jboss-parent/38/_remote.repositories").toGapvc());
```
```
org.jboss:jboss-parent:repositories:38:_remote
```
and including it in the results
3. Added a method `RepoDescriptor.listArtifacts(Path m2RepoDirectory)` that allows collecting complete artifact coordinates (instead …
=> Remove maven-metadata.xml from checksums and GAV(path) fixes

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/NotYetAlignedFromDependencyTree.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/addons/vertx/NotYetAlignedFromDependencyTreeTest.java
This commit fixes the integration between getting logs from Bifrost (via database and not from the final-log feature) and the NotYetAlignedFromDependencyTree.
Previously, the addon 'NotYetAlignedFromDependencyTree' expected the line to analyze to begin with:
```
[INFO] +
```
But Bifrost adds an extra info for some reason. The logs then become:
```
[INFO] [INFO] +
```
which doesn't match the line we want. This commit loosens the requirement to just have the '[INFO] +' line present somewhere.
Unit tests are written to make sure this logic is codified properly also.
=> Fix NotYetAlignedFromDependencyTree

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtilsTest.java
=> [NCL-7601] Translate artifact path to identifier instead of the identifier regex to path regex in RepoUtils#removeExcludedArtifacts

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/pnc/PncBuild.java, pnc/src/main/java/org/jboss/pnc/bacon/pnc/BuildCli.java
This commit removes the use of Bifrost live-logs feature for:
- PiG (since the final logs will already be present and we should use it for speed and reducing load on bifrost db search)
- align-logs (since we don't have a follow mode and we probably will invoke it after the alignment is done)
=> Use final-log for PiG and align-logs

pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/RepositoryUtilsTest.java
Fixes an issue when upstream Maven artifact versions end up in generated Maven repo ZIPs. For example [1]
This is caused by the current implementation of `RepositoryUtils.isCommunity(file)` that looks for `redhat-` in the complete absolute path of a file, which recognizes artifacts such as
```
/tmp/deliverable-generation15171812937701886995/rhaf-camel-4.8.0.redhat-00008-for-quarkus-3.15.0.CQ2-maven-repository/maven-repository/com/hierynomus/smbj/0.13.0/smbj-0.13.0.jar
```
as being Red Hat rebuilds due to the `rhaf-camel-4.8.0.redhat-00008-for-quarkus-3.15.0.CQ2-maven-repository` part.
FYI @svkcemk 
[1] https://download.eng.bos.redhat.com/rcm-guest/staging/rhaf/camel-extensions-for-quarkus-3.15.0.CQ1/extras/repository-artifact-list.txt
=> Fix RepositoryUtils.isCommunity(file)

pom.xml
this brings a fix to the WS client so that it uses a secure protocol
=> [NCL-8933] update pnc to version 3.0.4-SNAPSHOT

pom.xml
this brings a fix to the WS client so that it uses a secure protocol
=> [NCL-8933] update pnc to version 3.0.4

pig/src/main/java/org/jboss/pnc/bacon/pig/Cachi2Lockfile.java, pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/AddOnFactory.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/cachi2/Cachi2Lockfile.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/cachi2/Cachi2LockfileAddon.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/cachi2/Cachi2LockfileGenerator.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/addons/cachi2/YamlUtil.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoDescriptor.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ResolvedArtifactCollector.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/ResolvedGav.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/visitor/ArtifactVisit.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/visitor/ArtifactVisitor.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/visitor/FileSystemArtifactRepository.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/visitor/FileSystemArtifactVisit.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/visitor/VisitableArtifactRepository.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/GAV.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/BomMultiStepRepositoryStrategyTest.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/MultiStepBomBasedRepositoryTestBase.java
Cachi2 lockfiles are a way to prefetch PNC content into Konflux pipelines for MRRC release and container image building purposes.
This change allows generating Cachi2 lock files in the following ways:
* by enabling an Bacon add-on;
* by enabling an option in the BOM Maven repository generation strategy;
* by calling `bacon pig cachi2lockfile path-to-maven-repo(,path-to-maven-repo)*` CLI command.
The doc PR is https://github.com/project-ncl/bacon/pull/1305
=> A Pig extension and a CLI command that generate Cachi2 lock files for Maven repository ZIPs

da/src/main/java/org/jboss/bacon/da/DaHelper.java
The call for getToken is replaced by getTokenSupplier, which will provide tokens on demand instead of having a hardcoded token.
=> Fix DA get authenticated client

licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/lgpl-3.0.txt
Adding a cached entry for https://www.gnu.org/licenses/lgpl-3.0.txt into the license generator cache that Dustin created.    
We are hitting a hang in CPaaS on this license : 
```
10:38:57  [INFO ] - Hit too many requests exception for url: http://www.gnu.org/licenses/lgpl-3.0.txt, remaining retries: 5, sleeping for 1 minutes
10:39:57  [INFO ] - Hit too many requests exception for url: http://www.gnu.org/licenses/lgpl-3.0.txt, remaining retries: 4, sleeping for 2 minutes
12:19:23  Cancelling nested steps due to timeout
12:19:23  Sending interrupt signal to process
12:19:23  Killing processes
12:19:23  kill finished with exit code 0
12:19:23  script returned exit code 143
```
=> Add cached entry for https://www.gnu.org/licenses/lgpl-3.0.txt

.gitignore
minor change - add **/.DS_Store to the .gitignore.    .DS_Store are files generated by Mac OS X's Finder file browser
=> Ignore Mac OS X .DS_Store Finder files

licenses-generator/src/main/resources/offline-license-mirror/www.apache.org/licenses/LICENSE-2.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/agpl-3.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/fdl-1.1, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/fdl-1.2, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/fdl-1.3, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/gpl-1.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/gpl-2.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/gpl-3.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/lgpl-2.1, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/lgpl-3.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/fdl-1.1, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/fdl-1.2, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/gpl-1.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/gpl-2.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/lgpl-2.0, licenses-generator/src/main/resources/offline-license-mirror/www.gnu.org/licenses/old-licenses/lgpl-2.1
Files without an extension was using the html content but it is prefered to have a plain text file.
=> Use license txt content for files without extension

pig/pom.xml, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileCache.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/FileDownloadUtils.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/utils/FileCacheTest.java, pom.xml
Note: this feature is currently disabled in this commit until we can customize it on the frontend CLI side.
Generating huge maven repositories involve downloading a lot of artifacts from Indy. This is true for Maven repository generation types of:
- GENERATE
- BUILD_GROUP
- DOWNLOAD
- BUILD_CONFIGS
- MILESTONE
If we need to run the maven repository generations several times in the same machine, the same downloads happen and this can consume a lot of time. It would be nice if we could cache those downloads to speed up the maven repository generations for re-runs.
This commit adds the ability to cache the downloads into a cache file, managed my MapDB. The cache file is limited to a max disk size of 5GB, and the older contents in the cache will automatically get evicted.
The key of the cache …
=> [NCL-9108] Add backend option to cache artifacts downloaded from Indy

pig/src/main/java/org/jboss/pnc/bacon/pig/Pig.java, pig/src/main/java/org/jboss/pnc/bacon/pig/PigFacade.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/repo/RepoManager.java, pig/src/main/java/org/jboss/pnc/bacon/pig/impl/utils/indy/Indy.java, pig/src/main/resources/indy-cache-settings.xml, pig/src/main/resources/indy-cache-temp-settings.xml, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/MultiStepBomBasedRepositoryTestBase.java, pig/src/test/java/org/jboss/pnc/bacon/pig/impl/repo/ResolveOnlyRepositoryTest.java
This commit adds caching features to the maven repo generation:
- RESOLVE_ONLY
- GENERATE
- (anything BOM based)
It does so by adding a new local m2 cache folder `~/.cache/bacon/m2-cache` which is initially empty. The first run of Maven repository generation will generate the maven repository. This repository content is then copied to the local m2 cache folder.
On subsequent runs, this m2 cache folder will be checked for content before trying to download from Indy. This should significantly speed up Maven repo generation.
This is useful when testing locally for different variants of the maven repository generation, where the BOM content won't change that much from runs.
To disable this feature, you can use the `--useLocalM2Cache=false` to disable the cache feature. It is set to true by …
=> [NCL-9108] Cache for RESOLVE_ONLY maven repo generation

pig/src/main/resources/rh-license-exceptions.json
Fix license for jackson-base, it was incorrectly being picked up as "Public License"
=> Fix incorrect license for jackson-base

cli/pom.xml
This will regenerate bacon_completion file every build, otherwise it just complained file is there and won't generate it. If there is no change in commands, file is identical and not flagged in git changes.
=> Use force to regenerate autocompletion file

common/pom.xml, config/src/main/java/org/jboss/pnc/bacon/config/ReqourConfig.java, pom.xml
@jomrazek The idea here is to allow the bacon code to be more easily reusable without conflicting with Quarkus. By changing the imports to only whats needed it avoids bringing the rest-client module which which brings in resteasy. I have also added a section to be able to configure Reqour in future.
=> NCL-9218 Add reqourConfig and simplify imports
